
package view;

import dao.ClientesDAO;
import dao.FuncionarioDAO;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Clientes;
import model.Funcionario;
import utilitario.Utilitarios;


public class FormularioFuncionarios extends javax.swing.JFrame {   //  JDialog
      
      public void listar(){
       FuncionarioDAO dao = new FuncionarioDAO();
       List<Funcionario> lista = dao.Listar();
        
       DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
       dados.setNumRows(0);
       for(Funcionario c : lista){
           dados.addRow(new Object[]{
           c.getId(),
           c.getNome(),
           c.getRg(),
           c.getCpf(),
           c.getEmail(),
           
           c.getSenha(),
           c.getCargo(),
           c.getNivel(),
           
           
           c.getTelefone(),        
           c.getCelular(),
           c.getCep(),
           c.getEndereco(),
           c.getNumero(),
           c.getComplemento(),
           c.getBairro(),
           c.getCidade(),
           c.getEstado()
               
       });
       }
       
   }
                 
   
    
    public FormularioFuncionarios() {
       // super(parent , modal);
        initComponents();
      
        
    }
  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_guias = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        cbfEstado = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        txtRg = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbfNilvel_acesso = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtPesquisarNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnpesquisar1 = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Paineltitulo = new javax.swing.JPanel();
        TituloCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionarios");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        painel_guias.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(454, 88, 0, 0);

        jLabel17.setText("Código");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(10, 10, 33, 15);

        txtCodigo.setEditable(false);
        jPanel2.add(txtCodigo);
        txtCodigo.setBounds(50, -1, 70, 30);

        jLabel18.setText("Nome");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 50, 40, 15);

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });
        jPanel2.add(txtNome);
        txtNome.setBounds(80, 40, 176, 30);

        btnPesquisar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/pesquisar1.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(btnPesquisar);
        btnPesquisar.setBounds(270, 0, 170, 70);

        jLabel19.setText("email");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 80, 60, 15);
        jPanel2.add(txtEmail);
        txtEmail.setBounds(90, 80, 176, 30);

        jLabel20.setText("Celular");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(280, 80, 80, 20);

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtCelular);
        txtCelular.setBounds(353, 80, 100, 30);

        jLabel21.setText("Telefone");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(460, 90, 42, 15);

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtTelefone);
        txtTelefone.setBounds(510, 80, 134, 30);

        jLabel22.setText("Cep");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(10, 140, 50, 15);

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtCep);
        txtCep.setBounds(70, 130, 133, 30);

        jLabel23.setText("Endereco ");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(210, 140, 90, 15);
        jPanel2.add(txtEndereco);
        txtEndereco.setBounds(310, 130, 180, 30);

        jLabel8.setText("nº");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(510, 140, 20, 15);
        jPanel2.add(txtNumero);
        txtNumero.setBounds(580, 130, 70, 30);

        jLabel24.setText("Bairro");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 180, 120, 20);
        jPanel2.add(txtBairro);
        txtBairro.setBounds(80, 170, 110, 30);

        jLabel25.setText("Cidade");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(210, 180, 100, 15);
        jPanel2.add(txtCidade);
        txtCidade.setBounds(270, 180, 120, 30);

        jLabel26.setText("Complemento ");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(400, 190, 100, 15);

        txtComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoActionPerformed(evt);
            }
        });
        jPanel2.add(txtComplemento);
        txtComplemento.setBounds(500, 180, 50, 30);

        cbfEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PE", "SP", "RJ", "MA", "AC", "AL", "BA", "MA", "SE", "RN", "CE", "AM", "RO", "PI", "PB", "MG", "MS", "RR", "TO", "PA" }));
        jPanel2.add(cbfEstado);
        cbfEstado.setBounds(490, 220, 80, 24);

        jLabel27.setText("RG:");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(10, 230, 50, 15);
        jPanel2.add(txtRg);
        txtRg.setBounds(60, 220, 110, 30);

        jLabel28.setText("CPF");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(180, 230, 50, 15);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtCpf);
        txtCpf.setBounds(230, 220, 100, 30);

        jLabel1.setText("Senha");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(310, 260, 40, 20);
        jPanel2.add(txtSenha);
        txtSenha.setBounds(390, 260, 130, 30);

        jLabel2.setText("Cargo");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(580, 190, 50, 15);
        jPanel2.add(txtCargo);
        txtCargo.setBounds(660, 180, 90, 30);

        jLabel3.setText("Nivel de Acesso");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 260, 110, 15);

        cbfNilvel_acesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adm", "Usu" }));
        cbfNilvel_acesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbfNilvel_acessoActionPerformed(evt);
            }
        });
        jPanel2.add(cbfNilvel_acesso);
        cbfNilvel_acesso.setBounds(110, 260, 160, 24);

        jLabel4.setText("Estado");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(360, 230, 70, 15);

        painel_guias.addTab("Dados Pessoais", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setText("Nome:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 10, 60, 20);

        txtPesquisarNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarNomeKeyReleased(evt);
            }
        });
        jPanel3.add(txtPesquisarNome);
        txtPesquisarNome.setBounds(100, 10, 190, 30);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "Rg", "Cpf", "Email", "Senha", "Cargo", "Nivel", "Telefone", "Celular", "Cep", "Endereco", "numero", "complemento", "Bairro", "Cidade", "Estado"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        tabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 740, 240);

        btnpesquisar1.setText("Pesquisar");
        btnpesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnpesquisar1);
        btnpesquisar1.setBounds(370, 10, 130, 25);

        painel_guias.addTab("consulta de Funcionários", jPanel3);

        btnNovo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/novo.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/salvar.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/editar.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/excluir.png"))); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/printer.png"))); // NOI18N
        jButton6.setText("IMPRIMIR");

        Paineltitulo.setBackground(new java.awt.Color(0, 0, 0));

        TituloCadastro.setBackground(new java.awt.Color(255, 255, 255));
        TituloCadastro.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TituloCadastro.setForeground(new java.awt.Color(255, 255, 255));
        TituloCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloCadastro.setText("CADASTRO DE FUNCIONÁRIOS");
        TituloCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PaineltituloLayout = new javax.swing.GroupLayout(Paineltitulo);
        Paineltitulo.setLayout(PaineltituloLayout);
        PaineltituloLayout.setHorizontalGroup(
            PaineltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TituloCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );
        PaineltituloLayout.setVerticalGroup(
            PaineltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineltituloLayout.createSequentialGroup()
                .addComponent(TituloCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_guias, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Paineltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Paineltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(painel_guias, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addComponent(btnExcluir)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 47, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(799, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        Funcionario obj = new Funcionario();
        obj.setNome(txtNome.getText());
        obj.setRg(txtRg.getText());
        obj.setCpf(txtCpf.getText());
        obj.setEmail(txtEmail.getText());
        
        obj.setSenha(txtSenha.getText());
        obj.setCargo(txtCargo.getText());
        obj.setNivel(cbfNilvel_acesso.getSelectedItem().toString());
        
        obj.setTelefone(txtTelefone.getText());
        obj.setCelular(txtCelular.getText());
        obj.setCep(txtCep.getText());
        obj.setEndereco(txtEndereco.getText());
        obj.setNumero(Integer.valueOf(txtNumero.getText()));
        obj.setComplemento(txtComplemento.getText());
        obj.setBairro(txtBairro.getText());
        obj.setCidade(txtCidade.getText());
        obj.setEstado(cbfEstado.getSelectedItem().toString());
        
        FuncionarioDAO dao = new FuncionarioDAO();
        dao.Salvar(obj);
        Utilitarios util = new Utilitarios();
        util.LimpaTela(jPanel2);
        
       
            
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

       String nome = "%"+txtPesquisarNome.getText()+"%";
       FuncionarioDAO dao = new FuncionarioDAO();
       List<Funcionario> lista = dao.Filtrar(nome);
        
       DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
       dados.setNumRows(0);
       for(Funcionario c : lista){
           dados.addRow(new Object[]{
           c.getId(),
           c.getNome(),
           c.getRg(),
           c.getCpf(),
           c.getEmail(),
           
           c.getSenha(),
           c.getCargo(),
           c.getNivel(),
           
           c.getTelefone(),
           c.getCelular(),
           c.getCep(),
           c.getEndereco(),
           c.getNumero(),
           c.getComplemento(),
           c.getBairro(),
           c.getCidade(),
           c.getEstado()
               
       });
       }
       
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        Utilitarios util = new Utilitarios();
        util.LimpaTela(jPanel2);
        txtCodigo.setEnabled(false);
        
        painel_guias.setSelectedIndex(0);
                     
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
     
  //aqui
    listar();
      
        
     
    }//GEN-LAST:event_formWindowActivated

    private void btnpesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisar1ActionPerformed

        String nome = "%"+txtPesquisarNome.getText()+"%";
       FuncionarioDAO dao = new FuncionarioDAO();
       List<Funcionario> lista = dao.Filtrar(nome);
        
       DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
       dados.setNumRows(0);
       for(Funcionario c : lista){
           dados.addRow(new Object[]{
           c.getId(),
           c.getNome(),
           c.getRg(),
           c.getCpf(),
           c.getEmail(),
           
           c.getSenha(),
           c.getCargo(),
           c.getNivel(),
           
          
           c.getTelefone(),
           c.getCelular(),
           c.getCep(),
           c.getEndereco(),
           c.getNumero(),
           c.getComplemento(),
           c.getBairro(),
           c.getCidade(),
           c.getEstado()
               
       });
       }
    }//GEN-LAST:event_btnpesquisar1ActionPerformed

    private void txtPesquisarNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarNomeKeyReleased
        // TODO add your handling code here:
        
       String nome = "%"+txtPesquisarNome.getText()+"%";
       FuncionarioDAO dao = new FuncionarioDAO();
       List<Funcionario> lista = dao.Filtrar(nome);
        
       DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
       dados.setNumRows(0);
       for(Funcionario c : lista){
           dados.addRow(new Object[]{
           c.getId(),
           c.getNome(),
           c.getRg(),
           c.getCpf(),
           c.getEmail(),
         
           c.getSenha(),
           c.getCargo(),
           c.getNivel(),
           
           c.getTelefone(),
           c.getCelular(),
           c.getCep(),
           c.getEndereco(),
           c.getNumero(),
           c.getComplemento(),
           c.getBairro(),
           c.getCidade(),
           c.getEstado()
               
       });
        
        
       }
        
    }//GEN-LAST:event_txtPesquisarNomeKeyReleased

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            
        String nome =  txtNome.getText();
        Funcionario obj = new Funcionario();
        FuncionarioDAO dao = new FuncionarioDAO();
        
        obj = dao.buscarFuncionario(nome);
        if(obj.getNome()!= null){
           txtCodigo.setText(String.valueOf(obj.getId()));
           txtNome.setText(obj.getNome());
           txtRg.setText(obj.getRg());
           txtCpf.setText(obj.getCpf());
           txtEmail.setText(obj.getEmail());
           txtTelefone.setText(obj.getTelefone());
           txtCelular.setText(obj.getCelular());
           txtCep.setText(obj.getCep());
           txtEndereco.setText(obj.getEndereco());
           txtNumero.setText(String.valueOf(obj.getNumero()));
           txtComplemento.setText(obj.getComplemento());
           txtBairro.setText(obj.getBairro());
           txtCidade.setText(obj.getCidade());
           cbfEstado.setSelectedItem(obj.getEstado());
           
        }else {
            JOptionPane.showMessageDialog(null, "Cliente nao encontrado");
        }
        
        
        }
        
        
    }//GEN-LAST:event_txtNomeKeyPressed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        
       int linha= tabela.getSelectedRow();
          if(linha==-1){
              return;
          }
        txtCodigo.setText(String.valueOf(tabela.getValueAt(linha,0)));
        txtNome.setText(String.valueOf(tabela.getValueAt(linha,1)));
        txtRg.setText(String.valueOf(tabela.getValueAt(linha,2)));
        txtCpf.setText(String.valueOf(tabela.getValueAt(linha,3)));
        txtEmail.setText(String.valueOf(tabela.getValueAt(linha,4)));
        txtSenha.setText(String.valueOf(tabela.getValueAt(linha,5)));
        txtCargo.setText(String.valueOf(tabela.getValueAt(linha,6)));
        cbfNilvel_acesso.setSelectedItem(String.valueOf(tabela.getValueAt(linha,7)));
        txtTelefone.setText(String.valueOf(tabela.getValueAt(linha,8)));
        txtCelular.setText(String.valueOf(tabela.getValueAt(linha,9)));
        txtCep.setText(String.valueOf(tabela.getValueAt(linha,10)));
        txtEndereco.setText(String.valueOf(tabela.getValueAt(linha,11)));
        txtNumero.setText(String.valueOf(tabela.getValueAt(linha,12)));
        txtComplemento.setText(String.valueOf(tabela.getValueAt(linha,13)));
        txtBairro.setText(String.valueOf(tabela.getValueAt(linha,14)));
        txtCidade.setText(String.valueOf(tabela.getValueAt(linha,15)));
        cbfEstado.setSelectedItem(String.valueOf(tabela.getValueAt(linha,16)));
        
        
        
        
        painel_guias.setSelectedIndex(0);
        
        
        
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        
           try {

        // 🔒 Verifica se selecionou na tabela
        if (tabela.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, 
                "Selecione um funcionário na tabela antes de editar!");
            return;
        }

        // 🔒 Validações obrigatórias
        if (txtNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nome não pode estar vazio!");
            return;
        }

        if (txtCpf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "CPF não pode estar vazio!");
            return;
        }

        if (txtEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email não pode estar vazio!");
            return;
        }

        // 📦 Objeto
        Funcionario obj = new Funcionario();

        obj.setNome(txtNome.getText());
        obj.setRg(txtRg.getText());
        obj.setCpf(txtCpf.getText());
        obj.setEmail(txtEmail.getText());
        obj.setSenha(txtSenha.getText());
        obj.setCargo(txtCargo.getText());

        // ✅ ComboBox correto para nível
        obj.setNivel(cbfNilvel_acesso.getSelectedItem().toString());

        obj.setTelefone(txtTelefone.getText());
        obj.setCelular(txtCelular.getText());
        obj.setCep(txtCep.getText());
        obj.setEndereco(txtEndereco.getText());

        // 🔢 Número (tratamento correto)
        if (txtNumero.getText().trim().isEmpty()) {
            obj.setNumero(0);
        } else {
            obj.setNumero(Integer.parseInt(txtNumero.getText()));
        }

        obj.setComplemento(txtComplemento.getText());
        obj.setBairro(txtBairro.getText());
        obj.setCidade(txtCidade.getText());
        obj.setEstado(cbfEstado.getSelectedItem().toString());

        obj.setId(Integer.valueOf(txtCodigo.getText()));

        // 💾 DAO
        FuncionarioDAO dao = new FuncionarioDAO();
        dao.Editar(obj);

        // 🧹 Limpar tela
        Utilitarios util = new Utilitarios();
        util.LimpaTela(jPanel2);

        JOptionPane.showMessageDialog(null, 
            "Funcionário atualizado com sucesso!");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, 
            "Digite apenas números no campo Número!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, 
            "Erro ao atualizar: " + e.getMessage());
    }
        
        
        
        
        
        
        
        
        
        //// ATÉ AQUI
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Funcionario obj = new Funcionario();
        obj.setId(Integer.valueOf(txtCodigo.getText()));
        FuncionarioDAO dao = new FuncionarioDAO();
        dao.Excluir(obj);
        Utilitarios util = new Utilitarios();
        util.LimpaTela(jPanel2);
        
        
        
        
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void cbfNilvel_acessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbfNilvel_acessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbfNilvel_acessoActionPerformed

    private void tabelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaKeyReleased
        // TODO add your handling code here:
        
         String nome = "%"+txtPesquisarNome.getText()+"%";
       FuncionarioDAO dao = new FuncionarioDAO();
       List<Funcionario> lista = dao.Filtrar(nome);
        
       DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
       dados.setNumRows(0);
       for(Funcionario c : lista){
           dados.addRow(new Object[]{
           c.getId(),
           c.getNome(),
           c.getRg(),
           c.getCpf(),
           c.getEmail(),
           
           c.getSenha(),
           c.getCargo(),
           c.getNivel(),
           
           c.getTelefone(),
           c.getCelular(),
           c.getCep(),
           c.getEndereco(),
           c.getNumero(),
           c.getComplemento(),
           c.getBairro(),
           c.getCidade(),
           c.getEstado()
               
       });
       }
    }//GEN-LAST:event_tabelaKeyReleased

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new FormularioFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Paineltitulo;
    private javax.swing.JLabel TituloCadastro;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnpesquisar1;
    private javax.swing.JComboBox<String> cbfEstado;
    private javax.swing.JComboBox<String> cbfNilvel_acesso;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane painel_guias;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPesquisarNome;
    private javax.swing.JTextField txtRg;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
