
package view;

import controledeestoque1.ConexaoBanco;
import dao.ClientesDAO;
import dao.MateriaPrimaDAO;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Clientes;
import model.MateriaPrima;
import utilitario.Utilitarios;
import java.sql.Connection;
import java.io.InputStream;

import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


// aqui Jdialog
public class FormularioMateriaPrima extends javax.swing.JFrame {
      
      public void listar(){
       MateriaPrimaDAO dao = new MateriaPrimaDAO();
       List<MateriaPrima> lista = dao.Listar();
        
       DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
       dados.setNumRows(0);
       for(MateriaPrima c : lista){
           dados.addRow(new Object[]{
           c.getId(),
           c.getDescricao(),
           c.getEstoque(),
           c.getUnidadeMedida(),
           c.getEstoqueMinimo(),
           c.getValorUnitario(),
          
       });
       }
       
   }
                 
   
    // retirei (java.awt.Frame parent, boolean modal)  eambaixo : super(parent, modal);
    public FormularioMateriaPrima() {
        
        initComponents();
      
        
    }
  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_guias = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtUnidadeMedida = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtEstoqueMinimo = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtValorUnitario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtPesquisarNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnpesquisar1 = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        Paineltitulo = new javax.swing.JPanel();
        TituloCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        painel_guias.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(454, 88, 0, 0);

        jLabel17.setText("Código");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(10, 10, 33, 15);

        txtCodigo.setEditable(false);
        jPanel2.add(txtCodigo);
        txtCodigo.setBounds(50, -1, 70, 30);

        jLabel18.setText("Descrição:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 50, 90, 15);

        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyPressed(evt);
            }
        });
        jPanel2.add(txtDescricao);
        txtDescricao.setBounds(120, 40, 200, 30);

        btnPesquisar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/pesquisar1.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(btnPesquisar);
        btnPesquisar.setBounds(400, 20, 180, 50);

        jLabel19.setText("Unidade de Medida ");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 90, 120, 15);
        jPanel2.add(txtUnidadeMedida);
        txtUnidadeMedida.setBounds(140, 80, 210, 30);

        jLabel22.setText("Estoque");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(10, 140, 50, 15);
        jPanel2.add(txtEstoque);
        txtEstoque.setBounds(130, 130, 180, 30);

        jLabel24.setText("Estoque Minimo");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 180, 120, 20);
        jPanel2.add(txtEstoqueMinimo);
        txtEstoqueMinimo.setBounds(130, 170, 150, 30);

        jLabel26.setText("Valor Unitário ");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(10, 220, 100, 15);

        txtValorUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorUnitarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtValorUnitario);
        txtValorUnitario.setBounds(130, 210, 50, 30);

        painel_guias.addTab("Dados Pessoais", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setText("Nome:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 10, 60, 20);

        txtPesquisarNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarNomeKeyReleased(evt);
            }
        });
        jPanel3.add(txtPesquisarNome);
        txtPesquisarNome.setBounds(100, 10, 190, 30);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Descricao", "Unid Medida", "Estoque", "Estoque Minimo", "Valor Unitario"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 740, 240);

        btnpesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/pesquisar1.png"))); // NOI18N
        btnpesquisar1.setText("Pesquisar");
        btnpesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnpesquisar1);
        btnpesquisar1.setBounds(370, 5, 130, 40);

        painel_guias.addTab("consulta de Clientes", jPanel3);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/novo.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/salvar.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/editar.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/excluir.png"))); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/printer.png"))); // NOI18N
        btnImprimir.setText("IMPRIMIR");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        Paineltitulo.setBackground(new java.awt.Color(0, 0, 0));

        TituloCadastro.setBackground(new java.awt.Color(255, 255, 255));
        TituloCadastro.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TituloCadastro.setForeground(new java.awt.Color(255, 255, 255));
        TituloCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloCadastro.setText("CADASTRO MATÉRIA PRIMA");
        TituloCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PaineltituloLayout = new javax.swing.GroupLayout(Paineltitulo);
        Paineltitulo.setLayout(PaineltituloLayout);
        PaineltituloLayout.setHorizontalGroup(
            PaineltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TituloCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PaineltituloLayout.setVerticalGroup(
            PaineltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineltituloLayout.createSequentialGroup()
                .addComponent(TituloCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_guias, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Paineltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimir)
                .addGap(0, 74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Paineltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(painel_guias, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnImprimir)
                        .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );

        setSize(new java.awt.Dimension(755, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        MateriaPrima obj = new MateriaPrima();
        obj.setDescricao(txtDescricao.getText());
        obj.setUnidadeMedida(txtUnidadeMedida.getText());
        obj.setEstoque(Double.parseDouble(txtEstoque.getText()));
        obj.setEstoqueMinimo(Double.parseDouble(txtEstoqueMinimo.getText()));
        obj.setValorUnitario(Double.parseDouble(txtValorUnitario.getText()));
      
      
        
        MateriaPrimaDAO dao = new MateriaPrimaDAO();
        dao.Salvar(obj);
        Utilitarios util = new Utilitarios();
        util.LimpaTela(jPanel2);
        
        JOptionPane.showMessageDialog(null,"Materia Prima Salva com sucesso");
            
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtValorUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorUnitarioActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        
        String descricao =  txtDescricao.getText();
        MateriaPrima obj = new MateriaPrima();
        MateriaPrimaDAO dao = new MateriaPrimaDAO();
        
        obj = dao.BuscarMateriaPrima(descricao);
        if(obj.getDescricao()!= null){
           txtCodigo.setText(String.valueOf(obj.getId()));
           txtDescricao.setText(obj.getDescricao());
           txtUnidadeMedida.setText(obj.getUnidadeMedida());
           txtEstoque.setText(String.valueOf(obj.getEstoque()));
           txtEstoqueMinimo.setText(String.valueOf(obj.getEstoqueMinimo()));
           txtValorUnitario.setText(String.valueOf(obj.getValorUnitario()));
          
           
        }else {
            JOptionPane.showMessageDialog(null, "Materia prima nao encontrado");
        }
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        Utilitarios util = new Utilitarios();
        util.LimpaTela(jPanel2);
        txtCodigo.setEnabled(false);
        
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
     
  
    listar();
      
        
     
    }//GEN-LAST:event_formWindowActivated

    private void btnpesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisar1ActionPerformed
        // TODO add your handling code here:
       String descricao = "%"+txtPesquisarNome.getText()+"%";
       MateriaPrimaDAO dao = new MateriaPrimaDAO();
       List<MateriaPrima> lista = dao.Filtrar(descricao);
        
       DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
       dados.setNumRows(0);
       for(MateriaPrima c : lista){
           dados.addRow(new Object[]{
           c.getId(),
           c.getDescricao(),
           c.getEstoque(),
           c.getUnidadeMedida(),
           c.getEstoqueMinimo(),
           c.getValorUnitario(),
           
               
       });
       }
    }//GEN-LAST:event_btnpesquisar1ActionPerformed

    private void txtPesquisarNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarNomeKeyReleased
        // TODO add your handling code here:
         String nome = "%"+txtPesquisarNome.getText()+"%";
       ClientesDAO dao = new ClientesDAO();
       List<Clientes> lista = dao.Filtrar(nome);
        
       DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
       dados.setNumRows(0);
       for(Clientes c : lista){
           dados.addRow(new Object[]{
           c.getId(),
           c.getNome(),
           c.getRg(),
           c.getCpf(),
           c.getEmail(),
           c.getTelefone(),
           c.getCelular(),
           c.getCep(),
           c.getEndereco(),
           c.getNumero(),
           c.getComplemento(),
           c.getBairro(),
           c.getCidade(),
           c.getEstado()
               
       });
        
        
       }
        
    }//GEN-LAST:event_txtPesquisarNomeKeyReleased

    private void txtDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            String nome =  txtDescricao.getText();
        Clientes obj = new Clientes();
        ClientesDAO dao = new ClientesDAO();
        
        obj = dao.BuscarCliente(nome);
        if(obj.getNome()!= null){
           txtCodigo.setText(String.valueOf(obj.getId()));
           txtDescricao.setText(obj.getNome());
           
           txtUnidadeMedida.setText(obj.getEmail());
           txtEstoque.setText(obj.getEndereco());
           
          
           txtEstoqueMinimo.setText(obj.getBairro());
            txtValorUnitario.setText(obj.getComplemento());
           
        }else {
            JOptionPane.showMessageDialog(null, "Cliente nao encontrado");
        }
        }
        
        
    }//GEN-LAST:event_txtDescricaoKeyPressed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        
        painel_guias.setSelectedIndex(0);
        txtCodigo.setText(tabela.getValueAt(tabela.getSelectedRow(),0).toString());
        txtDescricao.setText(tabela.getValueAt(tabela.getSelectedRow(),1).toString());
        txtUnidadeMedida.setText(tabela.getValueAt(tabela.getSelectedRow(),4).toString());
        txtEstoque.setText(tabela.getValueAt(tabela.getSelectedRow(),8).toString());
         txtEstoqueMinimo.setText(tabela.getValueAt(tabela.getSelectedRow(),11).toString());
        txtValorUnitario.setText(tabela.getValueAt(tabela.getSelectedRow(),10).toString());
       
        
        
        
        
        
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    if (txtDescricao.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nome não pode estar vazio ");
        return;
    }
    try {
        MateriaPrima obj = new MateriaPrima();
        obj.setId(Integer.parseInt(txtCodigo.getText()));
        txtCodigo.setEditable(false);
        obj.setDescricao(txtDescricao.getText());
        obj.setUnidadeMedida(txtUnidadeMedida.getText());
        obj.setEstoque(Double.parseDouble(txtEstoque.getText()));
        obj.setEstoqueMinimo(Double.parseDouble(txtEstoqueMinimo.getText()));
        obj.setValorUnitario(Double.parseDouble(txtValorUnitario.getText()));
        MateriaPrimaDAO dao = new MateriaPrimaDAO();
        dao.Editar(obj);
        Utilitarios util = new Utilitarios();
        util.LimpaTela(jPanel2);
        JOptionPane.showMessageDialog(null, "Materia Prima atualizado com sucesso!");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Digite apenas a descricao!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao editar: " + e.getMessage());
    }
       
            
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        MateriaPrima obj = new MateriaPrima();
        obj.setId(Integer.valueOf(txtCodigo.getText()));
        MateriaPrimaDAO dao = new MateriaPrimaDAO();
        dao.Excluir(obj);
        Utilitarios util = new Utilitarios();
        util.LimpaTela(jPanel2);
        
        
        
        
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        
        Connection conn = null;

    try {

        // a conexao
        conn = new ConexaoBanco().pegarConexao();

        // Carregar relatório do package
        InputStream relatorio = getClass().getResourceAsStream(
                "/relatorios/relatorioClientes.jasper"
        );

        if (relatorio == null) {
            JOptionPane.showMessageDialog(null, 
                "Relatório não encontrado!");
            return;
        }

     
        JasperPrint print = JasperFillManager.fillReport(
                relatorio,
                null,
                conn
        );

       
        JasperViewer.viewReport(print, false);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,
                "Erro ao gerar relatório: " + e.getMessage());
    }
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnImprimirActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //ativar a linha debaixo. 
               new FormularioMateriaPrima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Paineltitulo;
    private javax.swing.JLabel TituloCadastro;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnpesquisar1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane painel_guias;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtEstoqueMinimo;
    private javax.swing.JTextField txtPesquisarNome;
    private javax.swing.JTextField txtUnidadeMedida;
    private javax.swing.JTextField txtValorUnitario;
    // End of variables declaration//GEN-END:variables
}
