
package view;

import controledeestoque1.ConexaoBanco;
import dao.ClientesDAO;
import dao.FornecedorDAO;
import dao.ProdutoDAO;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Clientes;
import model.Fornecedor;
import model.Produto;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import utilitario.Utilitarios;


public class FormularioEstoque extends javax.swing.JFrame {
    
    
    
    int idproduto, qtdatualizada;
      
      public void listar(){
       ProdutoDAO dao = new ProdutoDAO();
       List<Produto> lista = dao.Listar();
          System.out.println(lista.size());
       DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
       dados.setNumRows(0);
       for(Produto p : lista){
           dados.addRow(new Object[]{
           p.getId(),
           p.getDescricao(),
           p.getPreco(),    
           p.getQtd_estoque(),
           
          p.getFornecedor().getNome()
           
               
       });
       }
       
   }
                 
   
    
    public FormularioEstoque() {
        //super(parent, modal);
        
        initComponents();
        listar();
      
        
    }
  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_guias = new javax.swing.JTabbedPane();
        paine_estoque = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        txtQtdAtual = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtQtd_nova = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        Paineltitulo = new javax.swing.JPanel();
        TituloCadastro = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formularios de Estoque");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        painel_guias.setBackground(new java.awt.Color(51, 51, 51));

        paine_estoque.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Produtos"));
        paine_estoque.setForeground(new java.awt.Color(255, 255, 255));
        paine_estoque.setLayout(null);
        paine_estoque.add(jLabel9);
        jLabel9.setBounds(454, 88, 0, 0);

        jLabel17.setText("Código");
        paine_estoque.add(jLabel17);
        jLabel17.setBounds(10, 35, 33, 20);

        txtCodigo.setEditable(false);
        paine_estoque.add(txtCodigo);
        txtCodigo.setBounds(50, 30, 50, 30);

        jLabel18.setText("Descricao");
        paine_estoque.add(jLabel18);
        jLabel18.setBounds(120, 50, 80, 15);

        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyPressed(evt);
            }
        });
        paine_estoque.add(txtDescricao);
        txtDescricao.setBounds(210, 40, 176, 30);

        btnPesquisar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/pesquisar1.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        paine_estoque.add(btnPesquisar);
        btnPesquisar.setBounds(500, 50, 150, 42);
        paine_estoque.add(txtQtdAtual);
        txtQtdAtual.setBounds(90, 80, 176, 30);

        jLabel23.setText("Quantidade");
        paine_estoque.add(jLabel23);
        jLabel23.setBounds(280, 90, 90, 15);
        paine_estoque.add(txtQtd_nova);
        txtQtd_nova.setBounds(370, 80, 80, 30);

        jLabel29.setText("Qtd Atual ");
        paine_estoque.add(jLabel29);
        jLabel29.setBounds(10, 80, 60, 15);

        tabela.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Descricao", "Preco", "qtd_estoque", "Fornecedor"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        paine_estoque.add(jPanel1);
        jPanel1.setBounds(0, 130, 740, 150);

        painel_guias.addTab("Dados Produtos", paine_estoque);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/printer.png"))); // NOI18N
        jButton6.setText("I");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        Paineltitulo.setBackground(new java.awt.Color(0, 0, 0));

        TituloCadastro.setBackground(new java.awt.Color(255, 255, 255));
        TituloCadastro.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TituloCadastro.setForeground(new java.awt.Color(255, 255, 255));
        TituloCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloCadastro.setText("ESTOQUE");
        TituloCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PaineltituloLayout = new javax.swing.GroupLayout(Paineltitulo);
        Paineltitulo.setLayout(PaineltituloLayout);
        PaineltituloLayout.setHorizontalGroup(
            PaineltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TituloCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PaineltituloLayout.setVerticalGroup(
            PaineltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineltituloLayout.createSequentialGroup()
                .addComponent(TituloCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAdicionar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/add1.png"))); // NOI18N
        btnAdicionar.setText("Adicionar ");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/sair_1.png"))); // NOI18N
        jButton1.setText("Retirar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/add1.png"))); // NOI18N
        jButton2.setText("Cadastrar Produto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/add1.png"))); // NOI18N
        jButton4.setText("Cadastrar  Produto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_guias, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Paineltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Paineltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(painel_guias, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(755, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
     
  //aqui
    listar();
      
        
     
    }//GEN-LAST:event_formWindowActivated

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:

        String nome =  txtDescricao.getText();

        Produto obj = new Produto();
        ProdutoDAO dao = new ProdutoDAO();

        Fornecedor  f = new Fornecedor();
        FornecedorDAO  daof = new FornecedorDAO();

        obj = dao.BuscarProdutos(nome);

        if(obj.getDescricao()!= null){
            txtCodigo.setText(String.valueOf(obj.getId()));
            txtDescricao.setText(obj.getDescricao());
            txtQtdAtual.setText(String.valueOf(obj.getQtd_estoque()));
            txtQtd_nova.setText(String.valueOf(obj.getQtd_estoque()));

            f = daof.buscarFornecedor(obj.getFornecedor().getNome());


        }else {
            JOptionPane.showMessageDialog(null, "Produto nao encontrado");
        }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyPressed

        if(evt.getKeyCode()== KeyEvent.VK_ENTER){

          String nome = "%" + txtDescricao.getText() + "%";

ProdutoDAO dao = new ProdutoDAO();

DefaultTableModel dados = (DefaultTableModel) tabela.getModel();

dados.setNumRows(0);

for(Produto p : dao.Listar()){

    dados.addRow(new Object[]{

        p.getId(),
        p.getDescricao(),
        p.getPreco(),
        p.getQtd_estoque(),
        p.getFornecedor().getNome()

    });

}
}
    }//GEN-LAST:event_txtDescricaoKeyPressed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        
        idproduto = Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
        txtCodigo.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
        txtDescricao.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
        txtQtdAtual.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
        
        
        
        
        
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        try {
            int qtdAtual,qtd_nova;
            qtdAtual = Integer.valueOf(txtQtdAtual.getText());
            qtd_nova = Integer.valueOf(txtQtd_nova.getText());
            qtdatualizada = qtdAtual + qtd_nova;
            ProdutoDAO daop = new ProdutoDAO();
            daop.adicionarEstoque(idproduto,qtdatualizada);
            
            JOptionPane.showMessageDialog(null, "Estoque Atualizado com sucesso");
            
            //txtQtdAtual.setText("");
            txtQtd_nova.setText("");
            
            txtQtd_nova.requestFocus();
            
            
          new Utilitarios().LimpaTela(jPanel1);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erro" + e);
        }
        
    }//GEN-LAST:event_btnAdicionarActionPerformed

                 
    
    
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
                      Connection conn = null;
    try {
        //  liga ao banco de dados 
        conn = new ConexaoBanco().pegarConexao();
        // Carregar o relatório
        InputStream relatorio = getClass().getResourceAsStream(
                "/relatorios/relatorioEstoque.jasper"
        );
        if (relatorio == null) {
            JOptionPane.showMessageDialog(null, 
                "Relatório não encontrado!");
            return;
        }
        JasperPrint print = JasperFillManager.fillReport(
                relatorio,
                null,
                conn
        );
        JasperViewer.viewReport(print, false);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,
                "Erro ao gerar relatório: " + e.getMessage());
    }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
      
        try {
            int qtdAtual,qtd_nova;
            qtdAtual = Integer.valueOf(txtQtdAtual.getText());
            qtd_nova = Integer.valueOf(txtQtd_nova.getText());
            qtdatualizada = qtdAtual - qtd_nova;
            ProdutoDAO daop = new ProdutoDAO();
            daop.adicionarEstoque(idproduto,qtdatualizada);
            
            JOptionPane.showMessageDialog(null, "Estoque Atualizado com sucesso");
            
            //txtQtdAtual.setText("");
            txtQtd_nova.setText("");
            
            txtQtd_nova.requestFocus();
            
            
          new Utilitarios().LimpaTela(jPanel1);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erro" + e);
        }
        
        
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         FormularioProduto fp = new FormularioProduto();
        
       fp.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         FormularioProduto fp = new FormularioProduto();
        
       fp.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Paineltitulo;
    private javax.swing.JLabel TituloCadastro;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel paine_estoque;
    private javax.swing.JTabbedPane painel_guias;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtQtdAtual;
    private javax.swing.JTextField txtQtd_nova;
    // End of variables declaration//GEN-END:variables
}
