
package view;

import controledeestoque1.ConexaoBanco;
import dao.ClientesDAO;
import dao.FornecedorDAO;
import dao.ProdutoDAO;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Clientes;
import model.Fornecedor;
import model.Produto;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import utilitario.Utilitarios;





public class FormularioProduto extends javax.swing.JFrame {
      private boolean editando = false;
      public void listar(){
       ProdutoDAO dao = new ProdutoDAO();
       List<Produto> lista = dao.Listar();
        
       DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
       dados.setNumRows(0);
       for(Produto p : lista){
           dados.addRow(new Object[]{
           p.getId(),
           p.getDescricao(),
           p.getPreco(),    
           p.getQtd_estoque(),
           
           p.getFornecedor().getNome()
           
               
       });
       }
   }
      
     public void listarFor() {

    FornecedorDAO dao = new FornecedorDAO();

    cbfFornecedor.removeAllItems();

    for(Fornecedor f : dao.Listar()) {

        cbfFornecedor.addItem(f);

    }
} 
  /*  public void listarFornecedores(){
        
        FornecedorDAO dao = new FornecedorDAO();
        
        for(Fornecedor f : dao.Listar()){
          cbfFornecedor.addItem(f);
          
    }
        
        
        
    }*/
     
    private boolean produtoSalvo = false;
    
    
    public FormularioProduto() {
       
        initComponents();
        listar();
        listarFornecedores();
      
        
    }
  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_guias = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtQtd_Estoque = new javax.swing.JTextField();
        cbfFornecedor = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtPesquisarNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnpesquisar1 = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        Paineltitulo = new javax.swing.JPanel();
        TituloCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produto");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        painel_guias.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(454, 88, 0, 0);

        jLabel17.setText("Código");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(30, 10, 40, 15);

        txtCodigo.setEditable(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        jPanel2.add(txtCodigo);
        txtCodigo.setBounds(90, 0, 90, 30);

        jLabel18.setText("Descricao");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(20, 50, 80, 15);

        txtDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescricaoFocusLost(evt);
            }
        });
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyPressed(evt);
            }
        });
        jPanel2.add(txtDescricao);
        txtDescricao.setBounds(120, 40, 176, 30);

        btnPesquisar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/pesquisar1.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(btnPesquisar);
        btnPesquisar.setBounds(330, 0, 210, 70);

        jLabel19.setText("Fornecedor");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(30, 130, 110, 20);

        txtPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecoFocusLost(evt);
            }
        });
        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        jPanel2.add(txtPreco);
        txtPreco.setBounds(90, 80, 176, 30);

        jLabel23.setText("Quantidade");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(280, 90, 90, 15);

        txtQtd_Estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtd_EstoqueActionPerformed(evt);
            }
        });
        jPanel2.add(txtQtd_Estoque);
        txtQtd_Estoque.setBounds(390, 80, 180, 30);

        cbfFornecedor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbfFornecedorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbfFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbfFornecedorMouseClicked(evt);
            }
        });
        cbfFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbfFornecedorActionPerformed(evt);
            }
        });
        jPanel2.add(cbfFornecedor);
        cbfFornecedor.setBounds(130, 130, 190, 30);

        jLabel29.setText("Preço");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(20, 90, 60, 15);

        painel_guias.addTab("Dados Produtos", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setText("Nome:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 10, 60, 20);

        txtPesquisarNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarNomeKeyReleased(evt);
            }
        });
        jPanel3.add(txtPesquisarNome);
        txtPesquisarNome.setBounds(100, 10, 190, 30);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Descricao", "Preco", "qtd_estoque", "Fornecedor"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 740, 240);

        btnpesquisar1.setText("Pesquisar");
        btnpesquisar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpesquisar1MouseClicked(evt);
            }
        });
        btnpesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnpesquisar1);
        btnpesquisar1.setBounds(370, 0, 160, 40);

        painel_guias.addTab("consulta de Produtos", jPanel3);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/novo.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/salvar.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/editar.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/excluir.png"))); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/printer.png"))); // NOI18N
        btnImprimir.setText("IMPRIMIR");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        Paineltitulo.setBackground(new java.awt.Color(0, 0, 0));

        TituloCadastro.setBackground(new java.awt.Color(255, 255, 255));
        TituloCadastro.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TituloCadastro.setForeground(new java.awt.Color(255, 255, 255));
        TituloCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloCadastro.setText("CADASTRO DE PRODUTOS");
        TituloCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PaineltituloLayout = new javax.swing.GroupLayout(Paineltitulo);
        Paineltitulo.setLayout(PaineltituloLayout);
        PaineltituloLayout.setHorizontalGroup(
            PaineltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TituloCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PaineltituloLayout.setVerticalGroup(
            PaineltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineltituloLayout.createSequentialGroup()
                .addComponent(TituloCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_guias, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Paineltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimir)
                .addGap(0, 74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Paineltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(painel_guias, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addComponent(btnExcluir)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(755, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
  
    
        
        if(txtDescricao.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Por favor preencha a descrição!");
        txtDescricao.requestFocus();
        return;
    }
    if(txtPreco.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null,"Por favor preencha o preço!");
        txtPreco.requestFocus();
        return;
    }
    if(txtQtd_Estoque.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null,"Por favor preencha a quantidade!");
        txtQtd_Estoque.requestFocus();
        return;
    }
    String descricao = txtDescricao.getText().trim().toLowerCase();
    
   // if(!descricao.isEmpty()){
     //   descricao = descricao.substring(0,1).toUpperCase()
   //             + descricao.substring(1);
  //  }
    Produto obj = new Produto();
    obj.setId(Integer.parseInt(txtCodigo.getText()));
    obj.setDescricao(descricao);
    obj.setPreco(Double.valueOf(txtPreco.getText().replace(",",".")));
    obj.setQtd_estoque(Integer.valueOf(txtQtd_Estoque.getText().replace(descricao, descricao)));
    obj.setFornecedor((Fornecedor) cbfFornecedor.getSelectedItem());
   
    ProdutoDAO dao = new ProdutoDAO();
    
 //   if(dao.existeDescricao(descricao)){
      //  JOptionPane.showMessageDialog(null, "Já existe um produto com essa descrição");
       // txtDescricao.requestFocus();
        //return;
  //  }
    
    if (editando) {
    dao.Editar(obj);
    editando = false;
    btnSalvar.setText("Salvar");
    JOptionPane.showMessageDialog(null, "Produto atualizado com sucesso!");
    return;
} else {
    boolean retorno = dao.salvar(obj);
    if(retorno){
        produtoSalvo = true;
        JOptionPane.showMessageDialog(null, "Produto salvo com sucesso");
    }
    
}
   
  
  
  
  
  

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        
        String nome =  txtDescricao.getText();
        
        Produto obj = new Produto();
        ProdutoDAO dao = new ProdutoDAO();
        
        Fornecedor  f = new Fornecedor();
        FornecedorDAO  daof = new FornecedorDAO();
        
        obj = dao.BuscarProdutos(nome);
        
        if(obj.getDescricao()!= null){
           txtCodigo.setText(String.valueOf(obj.getId()));
           txtDescricao.setText(obj.getDescricao());
           txtPreco.setText(String.valueOf(obj.getPreco()));
           txtQtd_Estoque.setText(String.valueOf(obj.getQtd_estoque()));
           
           f = daof.buscarFornecedor(obj.getFornecedor().getNome());
           
           cbfFornecedor.getModel().setSelectedItem(f);
           
        }else {
            JOptionPane.showMessageDialog(null, "Produto nao encontrado");
        }
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        produtoSalvo = false;
        Utilitarios util = new Utilitarios();
        util.LimpaTela(jPanel2);
        txtCodigo.setEnabled(false);
        
        btnSalvar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        txtDescricao.requestFocusInWindow();
        
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
     
  //aqui
    listar();
      
        
     
    }//GEN-LAST:event_formWindowActivated

    private void btnpesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisar1ActionPerformed
        // TODO add your handling code here:
       String nome = "%"+txtPesquisarNome.getText()+"%";
       ProdutoDAO dao = new ProdutoDAO();
       List<Produto> lista = dao.Filtrar(nome);
        
       DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
       dados.setNumRows(0);
       for(Produto c : lista){
           dados.addRow(new Object[]{
           c.getId(),
           c.getDescricao(),
           c.getPreco(),
           c.getQtd_estoque(),
           c.getFornecedor().getNome()
       });
       }
    }//GEN-LAST:event_btnpesquisar1ActionPerformed

    private void txtPesquisarNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarNomeKeyReleased
        // TODO add your handling code here:
      String nome = "%"+txtPesquisarNome.getText()+"%";
       ProdutoDAO dao = new ProdutoDAO();
       List<Produto> lista = dao.Filtrar(nome);
        
       DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
       dados.setNumRows(0);
       for(Produto c : lista){
           dados.addRow(new Object[]{
           c.getId(),
           c.getDescricao(),
           c.getPreco(),
           c.getQtd_estoque(),
           c.getFornecedor().getNome()
       });
       }
        
    }//GEN-LAST:event_txtPesquisarNomeKeyReleased

    private void txtDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyPressed
        
      
        //txtPreco.requestFocus();
        
        /*  if(evt.getKeyCode()== KeyEvent.VK_ENTER){
        
        String nome =  txtDescricao.getText();
            
        Produto obj = new Produto();
        ProdutoDAO dao = new ProdutoDAO();
        Fornecedor f = new Fornecedor();
        FornecedorDAO daof = new FornecedorDAO();
        
        obj = dao.BuscarProdutos(nome);
        if(obj.getDescricao()!= null){
           txtCodigo.setText(String.valueOf(obj.getId()));
           txtDescricao.setText(String.valueOf(obj.getDescricao()));
           txtPreco.setText(String.valueOf(obj.getPreco()));
           
           txtQtd_Estoque.setText(String.valueOf(obj.getQtd_estoque()));
           
           
           f = daof.buscarFornecedor(obj.getFornecedor().getNome());
           cbfFornecedor.getModel().setSelectedItem(nome);
        }else {
            JOptionPane.showMessageDialog(null, "Cliente nao encontrado");
        }
        }*/
        
        
    }//GEN-LAST:event_txtDescricaoKeyPressed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        
        painel_guias.setSelectedIndex(0);
        txtCodigo.setText(tabela.getValueAt(tabela.getSelectedRow(),0).toString());
        txtDescricao.setText(tabela.getValueAt(tabela.getSelectedRow(),1).toString());
        
        txtPreco.setText(tabela.getValueAt(tabela.getSelectedRow(),2).toString());
        
        txtQtd_Estoque.setText(tabela.getValueAt(tabela.getSelectedRow(),3).toString());
        
        
        Fornecedor f = new Fornecedor();
        FornecedorDAO daof = new FornecedorDAO();
        f = daof.buscarFornecedor(tabela.getValueAt(tabela.getSelectedRow(),4).toString());
        cbfFornecedor.removeAllItems();
        cbfFornecedor.getModel().setSelectedItem(f);
        
        
        
        
        
        
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
     
        editando = true;
        
        
        System.out.println("cliequei no botao editar");
        if(!produtoSalvo){
         JOptionPane.showMessageDialog(null, "Salve o produto antes de editar");
         return;
     } 
        try{
    Produto obj = new Produto();
    obj.setId(Integer.valueOf(txtCodigo.getText()));
    obj.setDescricao(txtDescricao.getText());
    obj.setPreco(Double.valueOf(txtPreco.getText().replace(",", ".")));
    obj.setQtd_estoque(
    Integer.valueOf(txtQtd_Estoque.getText()));
    Fornecedor f = (Fornecedor)
    cbfFornecedor.getSelectedItem();
    if(f == null){JOptionPane.showMessageDialog(null,"Selecione um fornecedor");
    return;}
    obj.setFornecedor(f);
            System.out.println("entrou no men editar");
            
    obj.setId(Integer.parseInt(txtCodigo.getText()));
            System.out.println("ID "+ obj.getId());
    ProdutoDAO daop = new ProdutoDAO();
           System.out.println("depois   de char editar");
        System.out.println(obj.getId());
            System.out.println("antes editar");
    daop.Editar(obj);
            System.out.println("depois de editar");
        } catch (Exception e ){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e. getMessage());
        }
    Utilitarios util = new Utilitarios();
    util.LimpaTela(jPanel2);
    JOptionPane.showMessageDialog(null,"Salvou com sucesso.....!");
        
       
            
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(!produtoSalvo){
            JOptionPane.showMessageDialog(null, "Salve o produto antes de excluir");
            return; 
        }
        
        
        Produto obj = new Produto();
        obj.setId(Integer.valueOf(txtCodigo.getText()));
        ProdutoDAO dao = new ProdutoDAO();
        dao.Excluir(obj);
        Utilitarios util = new Utilitarios();
        util.LimpaTela(jPanel2);
        
        
        
        
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void cbfFornecedorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbfFornecedorAncestorAdded
        // TODO add your handling code here:
        
          
          
          
    }//GEN-LAST:event_cbfFornecedorAncestorAdded

    private void cbfFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbfFornecedorMouseClicked
        // TODO add your handling code here:
        
      /* FornecedorDAO dao = new FornecedorDAO();
          List<Fornecedor> lista = dao.Listar();
          cbfFornecedor.removeAllItems();
          for(Fornecedor f : lista){
              cbfFornecedor.addItem(f);
          }*/
        
        
        
    }//GEN-LAST:event_cbfFornecedorMouseClicked

    private void cbfFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbfFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbfFornecedorActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

        
        Connection conn = null;
    try {
        //  liga ao banco de dados 
        conn = new ConexaoBanco().pegarConexao();
        // Carregar o relatório
        InputStream relatorio = getClass().getResourceAsStream(
                "/relatorios/relatorioProduto.jasper"
        );
        if (relatorio == null) {
            JOptionPane.showMessageDialog(null, 
                "Relatório não encontrado!");
            return;
        }
        JasperPrint print = JasperFillManager.fillReport(
                relatorio,
                null,
                conn
        );
        JasperViewer.viewReport(print, false);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null,
                "Erro ao gerar relatório: " + e.getMessage());
    }
        
        
        
        
        
        
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
        
   String descricao = txtDescricao.getText().trim().toLowerCase();

    // Deixa apenas a primeira letra maiúscula
    if (!descricao.isEmpty()) {
        descricao = descricao.substring(0, 1).toUpperCase() + descricao.substring(1);
    }

    // Atualiza o campo na tela
    txtDescricao.setText(descricao);

    ProdutoDAO dao = new ProdutoDAO();

    // Verifica se o produto já existe
    if (dao.existeDescricao(descricao)) {
        JOptionPane.showMessageDialog(null, "Este produto já está cadastrado!");
        txtDescricao.requestFocus();
        txtDescricao.selectAll();
        return;
    }

    // Se não existir, vai para o campo Preço
    txtPreco.requestFocusInWindow();
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescricaoFocusLost
        // TODO add your handling code here:
        
 String descricao = txtDescricao.getText().trim().toLowerCase();

    // Deixa apenas a primeira letra maiúscula
    if (!descricao.isEmpty()) {
        descricao = descricao.substring(0, 1).toUpperCase() + descricao.substring(1);
    }

    // Atualiza o campo na tela
    txtDescricao.setText(descricao);

    ProdutoDAO dao = new ProdutoDAO();

    // Verifica se o produto já existe
    if (dao.existeDescricao(descricao)) {
        JOptionPane.showMessageDialog(null, "Este produto já está cadastrado!");
        txtDescricao.requestFocus();
        txtDescricao.selectAll();
        return;
    }

    // Se não existir, vai para o campo Preço
    txtPreco.requestFocusInWindow();
    }//GEN-LAST:event_txtDescricaoFocusLost

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
         try{
        double valor  = Double.parseDouble(txtPreco.getText().replace(",","."));
            java.text.DecimalFormat df = new java.text.DecimalFormat("#,##0.00");
            txtPreco.setText(df.format(valor));
        }catch(NumberFormatException e){
            txtPreco.setText("");
            
        
        
        }
        
        txtQtd_Estoque.requestFocusInWindow();        
        
        
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void txtPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecoFocusLost
        try{
            
            
            double valor  = Double.parseDouble(txtPreco.getText().replace(",","."));
            java.text.DecimalFormat df = new java.text.DecimalFormat("#,##0.00");
            txtPreco.setText(df.format(valor));
        }catch(NumberFormatException e){
            txtPreco.setText("");
            
        }
        
    
        
    }//GEN-LAST:event_txtPrecoFocusLost

    private void txtQtd_EstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtd_EstoqueActionPerformed
        // TODO add your handling code here:
        cbfFornecedor.requestFocusInWindow()
;        
        
    }//GEN-LAST:event_txtQtd_EstoqueActionPerformed

    private void btnpesquisar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpesquisar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpesquisar1MouseClicked

    
    
    public void listarFornecedores(){

    FornecedorDAO dao = new FornecedorDAO();

    List<Fornecedor> lista = dao.Listar();

    cbfFornecedor.removeAllItems();

    for(Fornecedor f : lista){

        cbfFornecedor.addItem(f);
    }
}
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new FormularioProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Paineltitulo;
    private javax.swing.JLabel TituloCadastro;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnpesquisar1;
    private javax.swing.JComboBox cbfFornecedor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane painel_guias;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtPesquisarNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQtd_Estoque;
    // End of variables declaration//GEN-END:variables
}
