/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controledeestoque1.ConexaoBanco;
import dao.ItensVendasDAO;
import dao.ProdutoDAO;
import dao.VendasDAO;
import java.io.InputStream;
import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Clientes;
import model.ItemVendas;
import javax.swing.table.DefaultTableModel;
import model.Funcionario;
import model.Produto;
import model.Vendas;
import java.sql.Connection;

import java.util.HashMap;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.view.JasperViewer;

public class FormularioPagamento extends javax.swing.JFrame {

    ItemVendas obj = new ItemVendas();
    Clientes clientes = new Clientes();

    DefaultTableModel meus_produtos;

    public FormularioPagamento() {
        initComponents();

       // txtDinheiro.setText("");
      //  txtCartao.setText("");
       // txtCheque.setText("");
        //txtTroco.setText("");
double dinheiro = 0;
double cartao = 0;
double cheque = 0;

if(!txtDinheiro.getText().trim().isEmpty()){
    dinheiro = Double.parseDouble(txtDinheiro.getText());
}

if(!txtCartao.getText().trim().isEmpty()){
    cartao = Double.parseDouble(txtCartao.getText());
}

if(!txtCheque.getText().trim().isEmpty()){
    cheque = Double.parseDouble(txtCheque.getText());
}

double totalPago = dinheiro + cartao + cheque;

if(txtTotal.getText().trim().isEmpty()){
    //JOptionPane.showMessageDialog(null, "Total da venda vazio!");
    return;
}

double totalVenda = Double.parseDouble(txtTotal.getText());

double troco = totalPago - totalVenda;

txtTroco.setText(String.valueOf(troco));   

        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDinheiro = new javax.swing.JTextField();
        txtCartao = new javax.swing.JTextField();
        txtCheque = new javax.swing.JTextField();
        txtTroco = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pagamento");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario de Pagamento");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PAGAMENTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 560, 110);

        jLabel2.setText("dinheiro");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 150, 60, 15);

        jLabel3.setText("cartão");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 190, 50, 15);

        jLabel4.setText("cheque");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 230, 50, 15);

        jLabel5.setText("troco");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 260, 50, 15);

        jLabel6.setText("total");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 300, 60, 15);

        txtDinheiro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtDinheiro);
        txtDinheiro.setBounds(90, 139, 80, 30);

        txtCartao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCartao);
        txtCartao.setBounds(90, 180, 80, 30);

        txtCheque.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCheque);
        txtCheque.setBounds(90, 219, 80, 30);

        txtTroco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTroco.setEnabled(false);
        getContentPane().add(txtTroco);
        txtTroco.setBounds(90, 250, 80, 40);

        txtTotal.setEnabled(false);
        getContentPane().add(txtTotal);
        txtTotal.setBounds(90, 300, 100, 50);

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        jScrollPane1.setViewportView(txtObservacao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 170, 230, 140);

        jLabel7.setText("Observação");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 140, 100, 15);

        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/iconfinder_Finance_loan_money_1889199.png"))); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPagar);
        btnPagar.setBounds(250, 330, 150, 74);

        setSize(new java.awt.Dimension(574, 486));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:

       // double dinheiro, cartao, cheque, totalVenda, troco, totalPago;

        //dinheiro = Double.valueOf(txtDinheiro.getText());
        //cartao = Double.valueOf(txtCartao.getText());
        //cheque = Double.valueOf(txtCheque.getText());
       // totalVenda = Double.valueOf(txtTotal.getText());

       // totalPago = dinheiro + cartao + cheque;
       // troco = totalPago - totalVenda;

       // txtTroco.setText(String.valueOf(troco));

double dinheiro = 0;
double cartao = 0;
double cheque = 0;
double totalVenda = 0;
double troco;
double totalPago;

if(!txtDinheiro.getText().trim().isEmpty()){
    dinheiro = Double.valueOf(txtDinheiro.getText());
}

if(!txtCartao.getText().trim().isEmpty()){
    cartao = Double.valueOf(txtCartao.getText());
}

if(!txtCheque.getText().trim().isEmpty()){
    cheque = Double.valueOf(txtCheque.getText());
}

if(!txtTotal.getText().trim().isEmpty()){
    totalVenda = Double.valueOf(txtTotal.getText());
}else{
    //JOptionPane.showMessageDialog(null, "Total da venda vazio!");
    return;
}

totalPago = dinheiro + cartao + cheque;

troco = totalPago - totalVenda;


DecimalFormat df = new DecimalFormat("0.00");
txtTroco.setText(df.format(troco));



//txtTroco.setText(String.valueOf(troco));
       
       
       
       
       
       
        
        
        
        
        // AQUI  
        if (totalPago >= totalVenda) {

            Vendas v = new Vendas();
            v.setClientes(clientes);
            
            Date agora = new Date();
            v.setData_venda(agora);
            
            v.setTotal_venda(totalVenda);
            
            v.setObservacao(txtObservacao.getText());

            Funcionario f = new Funcionario();
            f.setId(6);
            v.setFuncionario(f);
            try{
                
            VendasDAO vd = new VendasDAO();
            vd.Salvar(v);
            int idVenda = vd.retornarUltimoIdVenda();
            
            ItensVendasDAO itensDAO = new ItensVendasDAO();
            for(int i = 0;i < meus_produtos.getRowCount(); i++ ){
            ItemVendas item = new ItemVendas();

    int idProduto = Integer.parseInt(meus_produtos.getValueAt(i, 0).toString());
    int qtd = Integer.parseInt(meus_produtos.getValueAt(i, 2).toString());
    double subtotal = Double.parseDouble(meus_produtos.getValueAt(i, 4).toString());

    item.setVendas(v);

    Produto p = new Produto();
    p.setId(idProduto);
    item.setProduto(p);

    item.setQtd(qtd);
    item.setSubtotal(subtotal);

    itensDAO.salvar(item);
                
                
                
            }

           
            v.setNumeroNota(v.getId() +5);
            vd.atualizarNumeroNota(v);
            
            HashMap<String, Object> parametros = new HashMap<>();
            System.out.println("id vendas" + v.getId());
            
            
            parametros.put("ID_VENDA", v.getId());
            Connection conn = new ConexaoBanco().pegarConexao();
            try {
                
                 InputStream is = getClass().getResourceAsStream("/relatorios/nota_fiscal.jasper");

                if (is == null) {
                  JOptionPane.showMessageDialog(null, "relatorio não enonctrado");
                  return;
               }
                
               
                JasperPrint print = JasperFillManager.fillReport(
                        is,
                        parametros,
                        conn  
                );
                JasperViewer.viewReport(print, false);
           } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "erro ao gerar nota:" + e.getMessage());
           }
            
            } catch(Exception e){
                
                JOptionPane.showMessageDialog(null, "Erro ao salvar venda:" + e.getMessage());
               return; 
            }
           JOptionPane.showMessageDialog(null, "Venda Realizada com sucesso ! ID: " + v.getId());
              
              System.out.println("entrou........ ");
              
              for (int i = 0; i < meus_produtos.getRowCount(); i++) {
                int qtd_estoque, qtd_comprada, qtd_atualizada;
                
                  System.out.println("looooo" +i);

            
                Produto p = new Produto();
                ProdutoDAO pd = new ProdutoDAO();
                ItemVendas item = new ItemVendas();
                item.setVendas(v);
               
                
                p.setId((int)Double.parseDouble(meus_produtos.getValueAt(i, 0).toString()));
                System.out.println("ID" + meus_produtos.getValueAt(i,0));
                item.setProduto(p);
                
                int qtd = (int)(Double.parseDouble(meus_produtos.getValueAt(i, 2).toString()));//2
                System.out.println("ID" + meus_produtos.getValueAt(i,2));
                item.setQtd(qtd);
                item.setSubtotal(Double.parseDouble(meus_produtos.getValueAt(i, 4).toString()));
                System.out.println("ID" + meus_produtos.getValueAt(i,4));

                qtd_estoque = pd.retornarQtdAtualEstoque(p.getId());
                qtd_comprada = Integer.valueOf(meus_produtos.getValueAt(i, 2).toString());
                qtd_atualizada = qtd_estoque - qtd_comprada;

                pd.baixaEstoque(p.getId(), qtd_atualizada);

                ItensVendasDAO ivd = new ItensVendasDAO();
                ivd.salvar(item);
            }
            
        


    }//GEN-LAST:event_btnPagarActionPerformed

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCartao;
    private javax.swing.JTextField txtCheque;
    private javax.swing.JTextField txtDinheiro;
    private javax.swing.JTextArea txtObservacao;
    public javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTroco;
    // End of variables declaration//GEN-END:variables
}
