/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controledeestoque1.ConexaoBanco;
import dao.ItensVendasDAO;
import dao.VendasDAO;
import java.io.InputStream;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;

import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ItemVendas;
import model.Vendas;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Tarciso
 */
public class FormularioHistorico extends javax.swing.JFrame {

    /**
     * Creates new form FormularioHistorico
     */
    public FormularioHistorico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtInicio = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFim = new javax.swing.JFormattedTextField();
        btnPesquisar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario Historico");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Consulta por data"));

        jLabel2.setText("Data inicio:");

        try {
            txtInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/20##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInicioActionPerformed(evt);
            }
        });
        txtInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInicioKeyPressed(evt);
            }
        });

        jLabel3.setText("Data Final : ");

        try {
            txtFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/20##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFimKeyPressed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/pesquisar1.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        btnPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPesquisarKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/printer.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(61, 61, 61)
                .addComponent(txtFim, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 730, 130);

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cliente", "data da venda", "total da venda", "Observações"
            }
        ));
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabela);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 230, 730, 210);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HISTORICO DETALHADO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 730, 70);

        setSize(new java.awt.Dimension(743, 471));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
        
       SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
       sdf.setLenient(false);
       
       java.util.Date inicioUtil = sdf.parse(txtInicio.getText())  ;
       java.util.Date fimUtil = sdf.parse(txtFim.getText())  ;
       
       java.sql.Date  data_inicio = new java.sql.Date(inicioUtil.getTime());
       java.sql.Date  data_fim = new java.sql.Date(fimUtil.getTime()); 
       
        VendasDAO vd = new VendasDAO();
        
        List<Vendas>lista= vd.historicoVendas(data_inicio, data_fim);
        
        DefaultTableModel historico = (DefaultTableModel)Tabela.getModel();
        historico.setNumRows(0);
        for(Vendas v : lista){
            historico.addRow(new Object[]{
                v.getId(),
                v.getClientes().getNome(),
                v.getData_venda(),
                v.getTotal_venda(),
                v.getObservacao()
            });
           }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null,"data invalida");
        }
            
            
            
            
            
            
       
        
        
        
        
                
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
       int linha = Tabela.getSelectedRow();
       if(linha == -1){
           JOptionPane.showMessageDialog(null, "selecione uma venda");
           return;
       }
          int IdVenda = Integer.parseInt(Tabela.getValueAt(linha,0).toString());
          String Cliente = Tabela.getValueAt(linha,1).toString();
          String dataVenda = Tabela.getValueAt(linha,2).toString();
          String totalVenda = Tabela.getValueAt(linha,3).toString();
          String Observacoes = Tabela.getValueAt(linha,4).toString();
           
           FormularioDetalheVenda fdv = new FormularioDetalheVenda();
                      
           fdv.setVisible(true);
           
           fdv.txtIdVenda.setText(String.valueOf(IdVenda));
           fdv.txtCliente.setText(String.valueOf(Cliente));
           fdv.txtDataVenda.setText(dataVenda);
           fdv.txtTotalVenda.setText(String.valueOf(totalVenda));
           fdv.txtObs.setText(Observacoes);
           
           
           int venda_id = Integer.valueOf(fdv.txtIdVenda.getText());
           ItensVendasDAO dao = new ItensVendasDAO();
           List<ItemVendas> lista = dao.listaItens(venda_id);
           DefaultTableModel dados = (DefaultTableModel) fdv.carrinho.getModel();
           for (ItemVendas i : lista){
               dados.addRow(new Object []{
                   i.getProduto().getId(),
                   i.getProduto().getDescricao(),
                   i.getQtd(),
                   i.getProduto().getPreco(),
                   i.getSubtotal()
               });
               
               
           }
           
           
           fdv.setVisible(true);
           
         
        
    }//GEN-LAST:event_TabelaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          
     try {

    Connection conexao = new ConexaoBanco().pegarConexao();

    SimpleDateFormat formato =
    new SimpleDateFormat("dd/MM/yyyy");

    java.util.Date data1 =
    formato.parse(txtInicio.getText());

    java.util.Date data2 =
    formato.parse(txtFim.getText());

    java.sql.Date dtInicio =
    new java.sql.Date(data1.getTime());

    java.sql.Date dtFim =
    new java.sql.Date(data2.getTime());

    Map parametros = new HashMap();

    parametros.put("data_inicio", dtInicio);
    parametros.put("data_fim", dtFim);

    JasperPrint print =
    JasperFillManager.fillReport(
    "src/relatorios/relatorioPagamentoDoDia.jasper",
    parametros,
    conexao);

    JasperViewer.viewReport(print, false);

} catch (Exception e) {

    JOptionPane.showMessageDialog(null,
    "Erro: " + e);

}
    
        
        //Connection conn = null;
    //try {
        //  liga ao banco de dados 
     //   conn = new ConexaoBanco().pegarConexao();
        // Carregar o relatório
     //   InputStream relatorio = getClass().getResourceAsStream(
       //         "/relatorios/relatorioPagamentoDoDia.jasper"
     //   );
      //  if (relatorio == null) {
      //      JOptionPane.showMessageDialog(null, 
      //          "Relatório não encontrado!");
      //      return;
       // }
      //  JasperPrint print = JasperFillManager.fillReport(
       //         relatorio,
      //          null,
      //          conn
      //  );
     //   JasperViewer.viewReport(print, false);
   // } catch (Exception e) {
   //     JOptionPane.showMessageDialog(null,
   //             "Erro ao gerar relatório: " + e.getMessage());
  //  }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInicioActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
       
        
        
        
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void txtInicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInicioKeyPressed
        // TODO add your handling code here:
        txtInicio.requestFocus();
        
        
    }//GEN-LAST:event_txtInicioKeyPressed

    private void btnPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPesquisarKeyPressed
        // TODO add your handling code here:
        btnPesquisar.doClick();
        
    }//GEN-LAST:event_btnPesquisarKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        txtInicio.setText("");
        txtFim.setText("");
        txtInicio.requestFocus();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtFimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFimKeyPressed
        // TODO add your handling code here:
       
        
        
    }//GEN-LAST:event_txtFimKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioHistorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField txtFim;
    private javax.swing.JFormattedTextField txtInicio;
    // End of variables declaration//GEN-END:variables
}
