
package view;

import dao.ClientesDAO;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Clientes;
import utilitario.Utilitarios;

// aqui Jdialog
public class FormularioCliente extends javax.swing.JFrame {
      
      public void listar(){
       ClientesDAO dao = new ClientesDAO();
       List<Clientes> lista = dao.Listar();
        
       DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
       dados.setNumRows(0);
       for(Clientes c : lista){
           dados.addRow(new Object[]{
           c.getId(),
           c.getNome(),
           c.getRg(),
           c.getCpf(),
           c.getEmail(),
           c.getTelefone(),
           c.getCelular(),
           c.getCep(),
           c.getEndereco(),
           c.getNumero(),
           c.getComplemento(),
           c.getBairro(),
           c.getCidade(),
           c.getEstado()
               
       });
       }
       
   }
                 
   
    // retirei (java.awt.Frame parent, boolean modal)  eambaixo : super(parent, modal);
    public FormularioCliente() {
        
        initComponents();
      
        
    }
  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_guias = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        cbfEstado = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        txtRg = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtPesquisarNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnpesquisar1 = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Paineltitulo = new javax.swing.JPanel();
        TituloCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        painel_guias.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(454, 88, 0, 0);

        jLabel17.setText("Código");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(10, 10, 33, 15);

        txtCodigo.setEditable(false);
        jPanel2.add(txtCodigo);
        txtCodigo.setBounds(50, -1, 70, 30);

        jLabel18.setText("Nome");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 50, 40, 15);

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });
        jPanel2.add(txtNome);
        txtNome.setBounds(56, 40, 200, 30);

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/pesquisar1.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(btnPesquisar);
        btnPesquisar.setBounds(270, 20, 180, 50);

        jLabel19.setText("email");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 80, 60, 15);
        jPanel2.add(txtEmail);
        txtEmail.setBounds(56, 80, 210, 30);

        jLabel20.setText("Celular");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(280, 80, 80, 20);

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtCelular);
        txtCelular.setBounds(353, 80, 110, 30);

        jLabel21.setText("Telefone");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(480, 90, 42, 15);

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtTelefone);
        txtTelefone.setBounds(530, 80, 170, 30);

        jLabel22.setText("Cep");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(10, 140, 50, 15);

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtCep);
        txtCep.setBounds(70, 130, 133, 30);

        jLabel23.setText("Endereco ");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(210, 140, 90, 15);
        jPanel2.add(txtEndereco);
        txtEndereco.setBounds(310, 130, 180, 30);

        jLabel8.setText("nº");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(510, 140, 20, 15);
        jPanel2.add(txtNumero);
        txtNumero.setBounds(580, 130, 70, 30);

        jLabel24.setText("Bairro");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 180, 120, 20);
        jPanel2.add(txtBairro);
        txtBairro.setBounds(70, 170, 150, 30);

        jLabel25.setText("Cidade");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(240, 180, 100, 15);
        jPanel2.add(txtCidade);
        txtCidade.setBounds(300, 170, 120, 30);

        jLabel26.setText("Complemento ");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(10, 220, 100, 15);

        txtComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoActionPerformed(evt);
            }
        });
        jPanel2.add(txtComplemento);
        txtComplemento.setBounds(90, 210, 50, 30);

        cbfEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PE", "SP", "RJ", "MA", "AC", "AL", "BA", "MA", "SE", "RN", "CE", "AM", "RO", "PI", "PB", "MG", "MS", "RR", "TO", "PA" }));
        jPanel2.add(cbfEstado);
        cbfEstado.setBounds(570, 180, 80, 24);

        jLabel27.setText("RG:");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(250, 255, 50, 20);
        jPanel2.add(txtRg);
        txtRg.setBounds(300, 250, 110, 30);

        jLabel28.setText("CPF");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(10, 250, 60, 15);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtCpf);
        txtCpf.setBounds(90, 250, 130, 30);

        jLabel1.setText("Estado:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(480, 180, 70, 20);

        painel_guias.addTab("Dados Pessoais", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setText("Nome:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 10, 60, 20);

        txtPesquisarNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarNomeKeyReleased(evt);
            }
        });
        jPanel3.add(txtPesquisarNome);
        txtPesquisarNome.setBounds(100, 10, 190, 30);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "Rg", "Cpf", "Email", "Telefone", "Celular", "Cep", "Endereco", "numero", "complemento", "Bairro", "Cidade", "Estado"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 740, 240);

        btnpesquisar1.setText("Pesquisar");
        btnpesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnpesquisar1);
        btnpesquisar1.setBounds(370, 10, 130, 25);

        painel_guias.addTab("consulta de Clientes", jPanel3);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/novo.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/salvar.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/editar.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/excluir.png"))); // NOI18N
        jButton5.setText("EXCLUIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/printer.png"))); // NOI18N
        jButton6.setText("IMPRIMIR");

        Paineltitulo.setBackground(new java.awt.Color(0, 0, 0));

        TituloCadastro.setBackground(new java.awt.Color(255, 255, 255));
        TituloCadastro.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TituloCadastro.setForeground(new java.awt.Color(255, 255, 255));
        TituloCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloCadastro.setText("CADASTRO DE CLIENTES ");
        TituloCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PaineltituloLayout = new javax.swing.GroupLayout(Paineltitulo);
        Paineltitulo.setLayout(PaineltituloLayout);
        PaineltituloLayout.setHorizontalGroup(
            PaineltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TituloCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PaineltituloLayout.setVerticalGroup(
            PaineltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaineltituloLayout.createSequentialGroup()
                .addComponent(TituloCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_guias, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Paineltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(0, 74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Paineltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(painel_guias, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6)
                        .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );

        setSize(new java.awt.Dimension(755, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        Clientes obj = new Clientes();
        obj.setNome(txtNome.getText());
        obj.setRg(txtRg.getText());
        obj.setCpf(txtCpf.getText());
        obj.setEmail(txtEmail.getText());
        obj.setTelefone(txtTelefone.getText());
        obj.setCelular(txtCelular.getText());
        obj.setCep(txtCep.getText());
        obj.setEndereco(txtEndereco.getText());
        obj.setNumero(Integer.valueOf(txtNumero.getText()));
        obj.setComplemento(txtComplemento.getText());
        obj.setBairro(txtBairro.getText());
        obj.setCidade(txtCidade.getText());
        obj.setEstado(cbfEstado.getSelectedItem().toString());
        
        ClientesDAO dao = new ClientesDAO();
        dao.Salvar(obj);
        Utilitarios util = new Utilitarios();
        util.LimpaTela(jPanel2);
        
        JOptionPane.showMessageDialog(null,"Salvou");
            
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        
        String nome =  txtNome.getText();
        Clientes obj = new Clientes();
        ClientesDAO dao = new ClientesDAO();
        
        obj = dao.BuscarCliente(nome);
        if(obj.getNome()!= null){
           txtCodigo.setText(String.valueOf(obj.getId()));
           txtNome.setText(obj.getNome());
           txtRg.setText(obj.getRg());
           txtCpf.setText(obj.getCpf());
           txtEmail.setText(obj.getEmail());
           txtTelefone.setText(obj.getTelefone());
           txtCelular.setText(obj.getCelular());
           txtCep.setText(obj.getCep());
           txtEndereco.setText(obj.getEndereco());
           txtNumero.setText(String.valueOf(obj.getNumero()));
           txtComplemento.setText(obj.getComplemento());
           txtBairro.setText(obj.getBairro());
           txtCidade.setText(obj.getCidade());
           cbfEstado.setSelectedItem(obj.getEstado());
           
        }else {
            JOptionPane.showMessageDialog(null, "Cliente nao encontrado");
        }
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        Utilitarios util = new Utilitarios();
        util.LimpaTela(jPanel2);
        txtCodigo.setEnabled(false);
        
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
     
  //aqui
    listar();
      
        
     
    }//GEN-LAST:event_formWindowActivated

    private void btnpesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisar1ActionPerformed
        // TODO add your handling code here:
       String nome = "%"+txtPesquisarNome.getText()+"%";
       ClientesDAO dao = new ClientesDAO();
       List<Clientes> lista = dao.Filtrar(nome);
        
       DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
       dados.setNumRows(0);
       for(Clientes c : lista){
           dados.addRow(new Object[]{
           c.getId(),
           c.getNome(),
           c.getRg(),
           c.getCpf(),
           c.getEmail(),
           c.getTelefone(),
           c.getCelular(),
           c.getCep(),
           c.getEndereco(),
           c.getNumero(),
           c.getComplemento(),
           c.getBairro(),
           c.getCidade(),
           c.getEstado()
               
       });
       }
    }//GEN-LAST:event_btnpesquisar1ActionPerformed

    private void txtPesquisarNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarNomeKeyReleased
        // TODO add your handling code here:
         String nome = "%"+txtPesquisarNome.getText()+"%";
       ClientesDAO dao = new ClientesDAO();
       List<Clientes> lista = dao.Filtrar(nome);
        
       DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
       dados.setNumRows(0);
       for(Clientes c : lista){
           dados.addRow(new Object[]{
           c.getId(),
           c.getNome(),
           c.getRg(),
           c.getCpf(),
           c.getEmail(),
           c.getTelefone(),
           c.getCelular(),
           c.getCep(),
           c.getEndereco(),
           c.getNumero(),
           c.getComplemento(),
           c.getBairro(),
           c.getCidade(),
           c.getEstado()
               
       });
        
        
       }
        
    }//GEN-LAST:event_txtPesquisarNomeKeyReleased

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            String nome =  txtNome.getText();
        Clientes obj = new Clientes();
        ClientesDAO dao = new ClientesDAO();
        
        obj = dao.BuscarCliente(nome);
        if(obj.getNome()!= null){
           txtCodigo.setText(String.valueOf(obj.getId()));
           txtNome.setText(obj.getNome());
           txtRg.setText(obj.getRg());
           txtCpf.setText(obj.getCpf());
           txtEmail.setText(obj.getEmail());
           txtTelefone.setText(obj.getTelefone());
           txtCelular.setText(obj.getCelular());
           txtCep.setText(obj.getCep());
           txtEndereco.setText(obj.getEndereco());
           txtNumero.setText(String.valueOf(obj.getNumero()));
           txtComplemento.setText(obj.getComplemento());
           txtBairro.setText(obj.getBairro());
           txtCidade.setText(obj.getCidade());
           cbfEstado.setSelectedItem(obj.getEstado());
           
        }else {
            JOptionPane.showMessageDialog(null, "Cliente nao encontrado");
        }
        }
        
        
    }//GEN-LAST:event_txtNomeKeyPressed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        
        painel_guias.setSelectedIndex(0);
        txtCodigo.setText(tabela.getValueAt(tabela.getSelectedRow(),0).toString());
        txtNome.setText(tabela.getValueAt(tabela.getSelectedRow(),1).toString());
        txtRg.setText(tabela.getValueAt(tabela.getSelectedRow(),2).toString());
        txtCpf.setText(tabela.getValueAt(tabela.getSelectedRow(),3).toString());
        txtEmail.setText(tabela.getValueAt(tabela.getSelectedRow(),4).toString());
        txtTelefone.setText(tabela.getValueAt(tabela.getSelectedRow(),5).toString());
        txtCelular.setText(tabela.getValueAt(tabela.getSelectedRow(),6).toString());
        txtCep.setText(tabela.getValueAt(tabela.getSelectedRow(),7).toString());
        txtEndereco.setText(tabela.getValueAt(tabela.getSelectedRow(),8).toString());
        txtComplemento.setText(tabela.getValueAt(tabela.getSelectedRow(),9).toString());
        txtBairro.setText(tabela.getValueAt(tabela.getSelectedRow(),10).toString());
        txtCidade.setText(tabela.getValueAt(tabela.getSelectedRow(),11).toString());
        cbfEstado.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(),12).toString());
        
        
        
        
        
        
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        
         // 🔒 Validação da seleção   seleciona uma tabela 
    if (tabela.getSelectedRow() == -1) {
        JOptionPane.showMessageDialog(null, "Selecione um cliente na tabela!");
        return;
    }

    // 🔒 Validação de campos obrigatórios
    if (txtNome.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nome não pode estar vazio ");
        return;
    }

    if (txtNumero.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Número do endereço não pode estar vazio!");
        return;
    }

    try {
        Clientes obj = new Clientes();
        
        obj.setId(Integer.parseInt(txtCodigo.getText()));
        txtCodigo.setEditable(false);
        obj.setNome(txtNome.getText());
        obj.setRg(txtRg.getText());
        obj.setCpf(txtCpf.getText());
        obj.setEmail(txtEmail.getText());
        obj.setTelefone(txtTelefone.getText());
        obj.setCelular(txtCelular.getText());
        obj.setCep(txtCep.getText());
        obj.setEndereco(txtEndereco.getText());

        // 🔥 Conversões seguras
        obj.setNumero(Integer.parseInt(txtNumero.getText()));
        

        obj.setComplemento(txtComplemento.getText());
        obj.setBairro(txtBairro.getText());
        obj.setCidade(txtCidade.getText());
        obj.setEstado(cbfEstado.getSelectedItem().toString());

        ClientesDAO dao = new ClientesDAO();
        dao.Editar(obj);

        Utilitarios util = new Utilitarios();
        util.LimpaTela(jPanel2);

        JOptionPane.showMessageDialog(null, "Cliente atualizado com sucesso!");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Digite apenas números nos campos Código e Número!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao editar: " + e.getMessage());
    }
       
            
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Clientes obj = new Clientes();
        obj.setId(Integer.valueOf(txtCodigo.getText()));
        ClientesDAO dao = new ClientesDAO();
        dao.Excluir(obj);
        Utilitarios util = new Utilitarios();
        util.LimpaTela(jPanel2);
        
        
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //ativar a linha debaixo. 
               new FormularioCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Paineltitulo;
    private javax.swing.JLabel TituloCadastro;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnpesquisar1;
    private javax.swing.JComboBox<String> cbfEstado;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane painel_guias;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPesquisarNome;
    private javax.swing.JTextField txtRg;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
