/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controledeestoque1.ConexaoBanco;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tarciso
 */
public class RelatorioFinanceiro2 extends javax.swing.JFrame {
       private Connection conn;
       
       
       
       
       
    /**
     * Creates new form RelatorioFinanceiro2
     */
    public RelatorioFinanceiro2() {
        initComponents();
        
       //  tbRelatorioFinanceiro.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
       tbRelatorioFinanceiro.getColumnModel().getColumn(2).setPreferredWidth(300);
       tbRelatorioFinanceiro.setFont(new Font("Segoe UI", Font.PLAIN,14));
       tbRelatorioFinanceiro.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD,14));
       
        
        
       this.conn = new ConexaoBanco().pegarConexao();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCalendarDataInicial = new com.toedter.calendar.JCalendar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRelatorioFinanceiro = new javax.swing.JTable();
        jCalendarDataFinal = new com.toedter.calendar.JCalendar();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPesquisarGeral = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        cbTipoRelatorio = new javax.swing.JComboBox<>();
        btnPesquisar = new javax.swing.JButton();
        txtTotalVendas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        tbRelatorioFinanceiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Venda", "Data", "Cliente", "Forma de Pagamento", "Total(R$)"
            }
        ));
        jScrollPane1.setViewportView(tbRelatorioFinanceiro);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Relatório Financeiro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnPesquisarGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/buscar.png"))); // NOI18N
        btnPesquisarGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarGeralActionPerformed(evt);
            }
        });

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imgs/printer.png"))); // NOI18N
        btnImprimir.setText("jButton2");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        cbTipoRelatorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Total de Vendas", "Vendas em Dinheiro", "Venda via Pix", "Cartão de Débito", "Cartão de Crédito" }));

        btnPesquisar.setText("PESQUISAR ");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        txtTotalVendas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jCalendarDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCalendarDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPesquisarGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(cbTipoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txtTotalVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(446, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCalendarDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCalendarDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPesquisarGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbTipoRelatorio)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTotalVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

      private void pesquisar(Date dataInicial, Date dataFinal){
        
        try {

        String sql = "SELECT\n" +
"    v.id AS Venda,\n" +
"    v.data_venda AS Data,\n" +
"    c.nome AS Cliente,\n" +
"    v.forma_pagamento AS \"Forma de Pagamento\",\n" +
"    v.total_venda AS \"Total (R$)\"\n" +
"FROM tb_vendas v\n" +
"INNER JOIN tb_clientes c\n" +
"    ON c.id = v.cliente_id\n" +
"WHERE v.data_venda BETWEEN ? AND ?\n" +
"ORDER BY v.data_venda     ";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setDate(1, new java.sql.Date(dataInicial.getTime()));
        pst.setDate(2, new java.sql.Date(dataFinal.getTime()));

        ResultSet rs = pst.executeQuery();

        DefaultTableModel modelo = (DefaultTableModel) tbRelatorioFinanceiro.getModel();
        modelo.setRowCount(0);

        while (rs.next()) {

            modelo.addRow(new Object[]{
                rs.getInt("Venda"),
                new java.text.SimpleDateFormat("dd/MM/yyyy").format(rs.getDate("Data")),

               
                //rs.getDate("Data"),
                rs.getString("Cliente"),
                rs.getString("Forma de Pagamento"),
                
                String.format("R$ %,.2f",rs.getDouble("Total (R$)")).replace(",", "X").replace(".", ",").replace("X",".")
               // rs.getDouble("Total (R$)")
            });

        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
       
       
       
       
       
       
       
       
   }
    
    
    
    
    
    
    private void btnPesquisarGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarGeralActionPerformed
        
        Date dataInicial = jCalendarDataInicial.getDate();
        Date dataFinal = jCalendarDataFinal.getDate();
        
        pesquisar(dataInicial,dataFinal);
        
        
        
    }//GEN-LAST:event_btnPesquisarGeralActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        
       
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
    
    Date dataInicial = jCalendarDataInicial.getDate();
    Date dataFinal = jCalendarDataFinal.getDate();
         
    try {

    String tipo = cbTipoRelatorio.getSelectedItem().toString();

    String sql;
    
    
    if (tipo.equals("Venda via Pix")) {
    tipo = "Pix";
} else if (tipo.equals("Vendas em Dinheiro")) {
    tipo = "Dinheiro";
} else if (tipo.equals("Cartão de Débito")) {
    tipo = "Cartão Débito";
} else if (tipo.equals("Cartão de Crédito")) {
    tipo = "Cartão Crédito";
}

    
    
    
    
    

    if (tipo.equals("Todos") || tipo.equals("Total de Vendas")) {

        sql = "SELECT v.id, "
                + "v.data_venda, "
                + "c.nome AS Cliente, "
                + "v.forma_pagamento, "
                + "v.total_venda "
                + "FROM tb_vendas v "
                + "INNER JOIN tb_clientes c "
                + "ON c.id = v.cliente_id "
                + "WHERE v.data_venda BETWEEN ? AND ? "
                + "ORDER BY v.data_venda";

    } else {

        sql = "SELECT v.id, "
                + "v.data_venda, "
                + "c.nome AS Cliente, "
                + "v.forma_pagamento, "
                + "v.total_venda "
                + "FROM tb_vendas v "
                + "INNER JOIN tb_clientes c "
                + "ON c.id = v.cliente_id "
                + "WHERE v.data_venda BETWEEN ? AND ? "
                + "AND v.forma_pagamento = ? "
                + "ORDER BY v.data_venda";
    }

    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setDate(1, new java.sql.Date(dataInicial.getTime()));
    pst.setDate(2, new java.sql.Date(dataFinal.getTime()));

    if (!tipo.equals("Todos") && !tipo.equals("Total de Vendas")) {
        pst.setString(3, tipo);
    }

    ResultSet rs = pst.executeQuery();

    DefaultTableModel modelo = (DefaultTableModel) tbRelatorioFinanceiro.getModel();
    modelo.setRowCount(0);

    double total = 0;

    while (rs.next()) {

        modelo.addRow(new Object[]{
            rs.getInt("id"),
            new java.text.SimpleDateFormat("dd/MM/yyyy").format(rs.getDate("data_venda")),
            rs.getString("Cliente"),
            rs.getString("forma_pagamento"),
            String.format("R$ %,.2f",rs.getDouble("total_venda")).replace(",", "X").replace(".", ",").replace("X",".")
        });

        total += rs.getDouble("total_venda");
    }

    txtTotalVendas.setText(String.format("R$ %.2f", total));

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e.getMessage());
}

        
        
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioFinanceiro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioFinanceiro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioFinanceiro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioFinanceiro2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioFinanceiro2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPesquisarGeral;
    private javax.swing.JComboBox<String> cbTipoRelatorio;
    private com.toedter.calendar.JCalendar jCalendarDataFinal;
    private com.toedter.calendar.JCalendar jCalendarDataInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbRelatorioFinanceiro;
    private javax.swing.JTextField txtTotalVendas;
    // End of variables declaration//GEN-END:variables
}
